### ISSUE TITLE
Do not throw panic on missing cov or cor files

### ISSUE THREAD

**Issue by david-lyder** [metrumresearchgroup/babylon#38]
# Summary
Generation for cor and cov files is optional, do not throw panic if files are not found.

To exercise summary:
from: github.com/metrumresearchgroup/babylon/testdata/example-models/nonmem/IOVMM
bbi summary --json 2

# Tests

- summary_test.go
     - TestSummary

**Comment by david-lyder** [comment]
### Before fix:

from: github.com/metrumresearchgroup/babylon/testdata/example-models/nonmem/IOVMM
bbi summary --json 2
p
anic: open /Users/davidl/go/src/github.com/metrumresearchgroup/babylon/testdata/example-models/nonmem/IOVMM/**10.cov: no such file or directory**

goroutine 1 [running]:
github.com/metrumresearchgroup/babylon/parsers/nmparser.GetModelOutput(0x7ffeefbffb84, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/parsers/nmparser/get_model_output.go:56 +0x110e
github.com/metrumresearchgroup/babylon/cmd.summary(0x193b500, 0xc000067360, 0x1, 0x1)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/cmd/summary.go:44 +0xa4
github.com/spf13/cobra.(*Command).execute(0x193b500, 0xc000067310, 0x1, 0x1, 0x193b500, 0xc000067310)
	/Users/davidl/go/src/github.com/metrumresearchgroup/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x193ad80, 0x12, 0xc00014df00, 0x1)
	/Users/davidl/go/src/github.com/metrumresearchgroup/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/davidl/go/src/github.com/metrumresearchgroup/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/metrumresearchgroup/babylon/cmd.Execute(0x1600f40, 0x18)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/cmd/root.go:58 +0xe5
main.main()
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/cmd/bbi/main.go:17 +0x39

**Comment by david-lyder** [comment]
### After fix:

bbi summary 10 
LEM 10 mixture model and IOV on CL
Dataset: ../MixSim.CSV
Records: 13500   Observations: 12600  Patients: 300
Estimation Method(s):
 - First Order
+-------+-------------+----------+--------------+
| THETA |    NAME     | ESTIMATE | STDERR (RSE) |
+-------+-------------+----------+--------------+
| TH 1  | 1. CL POP 1 | 14.2204  | 0 (0.0%)     |
| TH 2  | 2. V        | 100.996  | 0 (0.0%)     |
| TH 3  | 3. WT ON CL | 0.824135 | 0 (0.0%)     |
| TH 4  | 4. WT ON V  | 0.988974 | 0 (0.0%)     |
| TH 5  | 5. CL POP 2 | 1.70925  | 0 (0.0%)     |
+-------+-------------+----------+--------------+
+--------+------+----------+-----------------+
| OMEGA  | ETA  | ESTIMATE | SHRINKAGESD (%) |
+--------+------+----------+-----------------+
| O(0,0) | ETA1 | 0.049035 | 0.000000        |
| O(1,1) | ETA2 | 0.048215 | 0.000000        |
| O(2,2) | ETA3 | 0.035925 | 0.000000        |
| O(3,3) | ETA4 | 0.035925 | 0.000000        |
| O(4,4) | ETA5 | 0.035925 | 0.000000        |
+--------+------+----------+-----------------+
