### ISSUE TITLE
Allow shrinkage to have 0 values in summary table

### ISSUE THREAD

**Issue by david-lyder** [metrumresearchgroup/babylon#49]
# Summary
When moving shrinkage details from an object to a slice of objects, I added range checking on the slices that panics if there is an attempt to reach an out-of-bound index.  I don't think the panic is correct. I think it is better to return 0 values for the shrinkage values.

**Update**: There should be no padding required in the summary table function: func (results ModelOutput.  If arrays require resizing, it is done in GetModelOutput.
This bug was introduced when implementing #40.

# Tests
- summary_test.go
     - TestSummary

**Comment by david-lyder** [comment]
### Before change:

bbi summary 10 
panic: **ShrinkageDetails.Eta.SD range error**

goroutine 1 [running]:
github.com/metrumresearchgroup/babylon/parsers/nmparser.ModelOutput.Summary(0xc0000282b8, 0x5, 0xc000024300, 0x1c, 0xc0000d8860, 0x1c, 0x4026947ae147ae14, 0x3fe3333333333333, 0x16f, 0x4008cccccccccccd, ...)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/parsers/nmparser/summary.go:67 +0x15db
github.com/metrumresearchgroup/babylon/cmd.summary(0x193c500, 0xc0000c9340, 0x1, 0x1)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/cmd/summary.go:50 +0x237
github.com/spf13/cobra.(*Command).execute(0x193c500, 0xc0000c92f0, 0x1, 0x1, 0x193c500, 0xc0000c92f0)
	/Users/davidl/go/src/github.com/metrumresearchgroup/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x193bd80, 0x12, 0xc00015ff00, 0x1)
	/Users/davidl/go/src/github.com/metrumresearchgroup/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/davidl/go/src/github.com/metrumresearchgroup/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/metrumresearchgroup/babylon/cmd.Execute(0x16015e0, 0x18)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/cmd/root.go:58 +0xe5
main.main()
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/cmd/bbi/main.go:17 +0x39

**Comment by david-lyder** [comment]
### After change:

bbi summary 10
LEM 10 mixture model and IOV on CL
Dataset: ../MixSim.CSV
Records: 13500   Observations: 12600  Patients: 300
Estimation Method(s):
 - First Order
+-------+-------------+----------+--------------+
| THETA |    NAME     | ESTIMATE | STDERR (RSE) |
+-------+-------------+----------+--------------+
| TH 1  | 1. CL POP 1 | 14.2204  | 0 (0.0%)     |
| TH 2  | 2. V        | 100.996  | 0 (0.0%)     |
| TH 3  | 3. WT ON CL | 0.824135 | 0 (0.0%)     |
| TH 4  | 4. WT ON V  | 0.988974 | 0 (0.0%)     |
| TH 5  | 5. CL POP 2 | 1.70925  | 0 (0.0%)     |
+-------+-------------+----------+--------------+
+--------+------+----------+-----------------+
| OMEGA  | ETA  | ESTIMATE | SHRINKAGESD (%) |
+--------+------+----------+-----------------+
| O(0,0) | ETA1 | 0.049035 | 0               |
| O(1,1) | ETA2 | 0.048215 | 0               |
| O(2,2) | ETA3 | 0.035925 | 0               |
| O(3,3) | ETA4 | 0.035925 | 0               |
| O(4,4) | ETA5 | 0.035925 | 0               |
+--------+------+----------+-----------------+
