### ISSUE TITLE
OMEGA parameters not parsed correctly

### ISSUE THREAD

**Issue by david-lyder** [metrumresearchgroup/babylon#52]
### Summary
Not all mod/lst files have lines defining the size and structure of OMEGA. The current code looks for and parses the lines:
0OMEGA HAS SIMPLE DIAGONAL FORM WITH DIMENSION
or
0OMEGA HAS BLOCK FORM:
The result of not finding the "0OMEGA HAS " causes an index OOB error inparseParameterStructure as an array of zero lines is passed into the function.

**Proposal**
The length of OMEGA can be captured from the ext file (for example as OmegaCount). Then the first # of OmageCount lines in the lst file that start with "$OMEGA BLOCK" can be captured for the OMEGA values and possible the parameter name.  Note, these 3 (known) forms of "OMEGA BLOCK" must be supported:
**(1)**
$OMEGA BLOCK(3)
1                ;1 - CL 
2   3          ;2 - V1 
4   5   6    ;3 - V2 
**(2)**
OMEGA BLOCK(1) 0 FIX   ;4 - VMAX
**(3)**
$OMEGA BLOCK(1) SAME ;8 - IOVCL

### Tests
TestSummary
TestSummaryTable
note: after adding support for a new control stream

**Comment by david-lyder** [comment]
### Before change:

bbi summary 117.mod
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/metrumresearchgroup/babylon/parsers/nmparser.parseParameterStructure(0xc0001a98b0, 0x0, 0x375, 0xe, 0xc000162970, 0x1)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/parsers/nmparser/parse_parameter_structure.go:20 +0x223
github.com/metrumresearchgroup/babylon/parsers/nmparser.ParseParameterStructures(0xc0001a98b0, 0x4, 0x375, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/parsers/nmparser/parse_parameter_structure.go:54 +0x35d
github.com/metrumresearchgroup/babylon/parsers/nmparser.ParseLstEstimationFile(0xc0001a8000, 0x402, 0x500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/parsers/nmparser/parse_lst_file.go:417 +0x632
github.com/metrumresearchgroup/babylon/parsers/nmparser.GetModelOutput(0x7ffeefbffb7c, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/parsers/nmparser/get_model_output.go:27 +0x220
github.com/metrumresearchgroup/babylon/cmd.summary(0x193c500, 0xc0000b34e0, 0x1, 0x1)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/cmd/summary.go:44 +0xa4
github.com/spf13/cobra.(*Command).execute(0x193c500, 0xc0000b3490, 0x1, 0x1, 0x193c500, 0xc0000b3490)
	/Users/davidl/go/src/github.com/metrumresearchgroup/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x193bd80, 0x12, 0xc000163f00, 0x1)
	/Users/davidl/go/src/github.com/metrumresearchgroup/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/davidl/go/src/github.com/metrumresearchgroup/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/metrumresearchgroup/babylon/cmd.Execute(0x1601660, 0x18)
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/cmd/root.go:58 +0xe5
main.main()
	/Users/davidl/go/src/github.com/metrumresearchgroup/babylon/cmd/bbi/main.go:17 +0x39

**Comment by david-lyder** [comment]
### After simple change:
(return nil from the function parseParameterStructure if the array length of lines is zero):

**JSON (table output below):**
{
	"run_details": {
		"version": "7.3.0",
		"run_end": "Fri Jun 14 18:58:07 UTC 2019",
		"estimation_time": 141.13,
		"covariance_time": 196.63,
		"function_evaluations": 1075,
		"significant_digits": 2.4,
		"problem_text": "LEM RUN# 117 peds only: estimate WT:CL, WT:V1",
		"estimation_method": [
			"First Order Conditional Estimation with Interaction"
		],
		"data_set": "../../../data/derived/TAK0203.csv",
		"number_of_patients": 48,
		"number_of_obs": 480,
		"number_of_data_records": 2780,
		"output_files_used": [
			"117.lst",
			"117.ext",
			"117.grd"
		]
	},
	"run_heuristics": {
		"has_final_zero_gradient": "HeuristicFalse"
	},
	"parameters_data": [
		{
			"method": "TABLE NO.     1: First Order Conditional Estimation with Interaction: Goal Function=MINIMUM VALUE OF OBJECTIVE FUNCTION: Problem=1 Subproblem=0 Superproblem1=0 Iteration1=0 Superproblem2=0 Iteration2=0",
			"estimates": {
				"theta": [
					-1.56062,
					-1.69878,
					1.14882,
					0.716514,
					-1.27995,
					-1.24929,
					-0.556125,
					1.20988,
					-0.939965,
					0.118089,
					0.932728,
					0.0439451,
					1,
					0.75,
					0.75,
					0
				],
				"omega": [
					0.0892082,
					0.023791,
					0.0336301,
					-0.0667738,
					0.0292602,
					0.326591,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.0399471
				]
			},
			"std_err": {
				"theta": [
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				],
				"omega": [
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				]
			},
			"random_effect_sd": {
				"omega": [
					0.298677,
					0.434357,
					0.183385,
					-0.391202,
					0.279197,
					0.571481,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0.199868
				]
			},
			"random_effect_sdse": {},
			"fixed": {
				"theta": [
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					1,
					1,
					1,
					1
				],
				"omega": [
					0,
					0,
					0,
					0,
					0,
					0,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					0,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1
				]
			}
		}
	],
	"parameter_structures": {
		"Theta": 34,
		"Omega": null,
		"Sigma": [
			1
		]
	},
	"parameter_names": {
		"theta": [
			"1 - CLNEG (L/day) LN",
			"2 - CLPOS (L/day) LN",
			"3 - V1 (L) LN",
			"4 - V2 (L) LN",
			"5 - VMAX (mg/day) LN",
			"6 - Q (L/day) LN",
			"7 - KM (mcg/mL) LN",
			"8 - CLWT",
			"9 - CLALB",
			"10 - CLAVA",
			"11 - V1WT",
			"12 - CLDIAG  LN",
			"13 - V2WT",
			"14 - VMAXWT",
			"15 - QWT",
			"16 - CLAGE",
			"17 - CLTNF"
		]
	},
	"ofv": {
		"ofv_no_constant": 2793.497
	},
	"shrinkage_details": [
		{
			"eta": {
				"sd": [
					5.8003,
					10.744,
					17.452,
					100,
					100,
					100,
					100,
					55.298,
					5.8742,
					42.844
				]
			},
			"ebv": {
				"sd": [
					7.7348,
					11.098,
					14.879,
					0,
					0,
					0,
					100,
					41.842,
					31.648,
					31.833
				]
			},
			"eps": {
				"sd": [
					0
				],
				"vr": [
					0
				]
			}
		}
	],
	"covariance_theta": [
		{
			"Values": null,
			"Dim": 0
		}
	],
	"correlation_theta": [
		{
			"Values": null,
			"Dim": 0
		}
	]
}

**Table:**
bbi summary 117.mod

LEM RUN# 117 peds only: estimate WT:CL, WT:V1
Dataset: ../../../data/derived/TAK0203.csv
Records: 2780   Observations: 480  Patients: 48
Estimation Method(s):
 - First Order Conditional Estimation with Interaction
+-------+----------------------+-----------+--------------+
| THETA |         NAME         | ESTIMATE  | STDERR (RSE) |
+-------+----------------------+-----------+--------------+
| TH 1  | 1 - CLNEG (L/day) LN | -1.56062  | 0 (0.0%)     |
| TH 2  | 2 - CLPOS (L/day) LN | -1.69878  | 0 (0.0%)     |
| TH 3  | 3 - V1 (L) LN        | 1.14882   | 0 (0.0%)     |
| TH 4  | 4 - V2 (L) LN        | 0.716514  | 0 (0.0%)     |
| TH 5  | 5 - VMAX (mg/day) LN | -1.27995  | 0 (0.0%)     |
| TH 6  | 6 - Q (L/day) LN     | -1.24929  | 0 (0.0%)     |
| TH 7  | 7 - KM (mcg/mL) LN   | -0.556125 | 0 (0.0%)     |
| TH 8  | 8 - CLWT             | 1.20988   | 0 (0.0%)     |
| TH 9  | 9 - CLALB            | -0.939965 | 0 (0.0%)     |
| TH 10 | 10 - CLAVA           | 0.118089  | 0 (0.0%)     |
| TH 11 | 11 - V1WT            | 0.932728  | 0 (0.0%)     |
| TH 12 | 12 - CLDIAG  LN      | 0.0439451 | 0 (0.0%)     |
| TH 13 | 13 - V2WT            | 1         | 0 (0.0%)     |
| TH 14 | 14 - VMAXWT          | 0.75      | 0 (0.0%)     |
| TH 15 | 15 - QWT             | 0.75      | 0 (0.0%)     |
| TH 16 | 16 - CLAGE           | 0         | 0 (0.0%)     |
+-------+----------------------+-----------+--------------+
+-------+-----+----------+-----------------+
| OMEGA | ETA | ESTIMATE | SHRINKAGESD (%) |
+-------+-----+----------+-----------------+
+-------+-----+----------+-----------------+

**Comment by dpastoor** [comment]
excellent work on the quick change! yes i like the idea to grab from ext file, that makes ton of sense and will keep parsing much more consistent.

As a regression test, does this change still pass all existing models?

**Comment by dpastoor** [comment]
It looks like omega structure gets lost though now (in param structures omega is now NULL)

**Comment by dpastoor** [comment]
that is probably why the omega table isn't printing out

**Comment by david-lyder** [comment]
Existing tests pass with the quick fix (return nil). This is because all of our current control streams have an "0OMEGA HAS" line, so the "return nil" is never executed.

grep -in "0OMEGA HAS " */*.lst
BQL/2.lst:93:0OMEGA HAS SIMPLE DIAGONAL FORM WITH DIMENSION:   3
IOVMM/10.lst:98:0OMEGA HAS BLOCK FORM:
NonlinearCL/1.lst:107:0OMEGA HAS SIMPLE DIAGONAL FORM WITH DIMENSION:   3
TMDD/1.lst:144:0OMEGA HAS BLOCK FORM:
contpkpd/1.lst:86:0OMEGA HAS SIMPLE DIAGONAL FORM WITH DIMENSION:   6
meropenem/meropenem.lst:144:0OMEGA HAS SIMPLE DIAGONAL FORM WITH DIMENSION:   4
psp412404/402.lst:91:0OMEGA HAS SIMPLE DIAGONAL FORM WITH DIMENSION:   4

**Comment by david-lyder** [comment]
### Proposal
Update function ParseExtData to return "parameter_structures" data. This will follow the same pattern of getting the data from the lst first, and if the ext file exists, overwrite the data.

In the ParseExtData function, parse the line:
ITERATION    THETA1       THETA2       ...     SIGMA(1,1)   OMEGA(1,1)   OMEGA(2,1)   ...  OBJ

To get the number of THETA, SIGMA and OMEGA.
It appears in all current control streams that the OMEGA values are a block of values, so the function createDiagonalBlock can be used to populate the OMEGA "parameter_structures" data

**Comment by david-lyder** [comment]
A temp fix was implemented (another issue was opened to track #56)

### After temp fix:
bbi summary 117
2019/10/18 15:23:16 Error parsing Omega parameter structure, falling back to temporary solution, please notify the babylon development team
LEM RUN# 117 peds only: estimate WT:CL, WT:V1
Dataset: ../../../data/derived/TAK0203.csv
Records: 2780   Observations: 480  Patients: 48
Estimation Method(s):
 - First Order Conditional Estimation with Interaction
+-------+----------------------+-----------+--------------+
| THETA |         NAME         | ESTIMATE  | STDERR (RSE) |
+-------+----------------------+-----------+--------------+
| TH 1  | 1 - CLNEG (L/day) LN | -1.56062  | 0 (0.0%)     |
| TH 2  | 2 - CLPOS (L/day) LN | -1.69878  | 0 (0.0%)     |
| TH 3  | 3 - V1 (L) LN        | 1.14882   | 0 (0.0%)     |
| TH 4  | 4 - V2 (L) LN        | 0.716514  | 0 (0.0%)     |
| TH 5  | 5 - VMAX (mg/day) LN | -1.27995  | 0 (0.0%)     |
| TH 6  | 6 - Q (L/day) LN     | -1.24929  | 0 (0.0%)     |
| TH 7  | 7 - KM (mcg/mL) LN   | -0.556125 | 0 (0.0%)     |
| TH 8  | 8 - CLWT             | 1.20988   | 0 (0.0%)     |
| TH 9  | 9 - CLALB            | -0.939965 | 0 (0.0%)     |
| TH 10 | 10 - CLAVA           | 0.118089  | 0 (0.0%)     |
| TH 11 | 11 - V1WT            | 0.932728  | 0 (0.0%)     |
| TH 12 | 12 - CLDIAG  LN      | 0.0439451 | 0 (0.0%)     |
| TH 13 | 13 - V2WT            | 1         | 0 (0.0%)     |
| TH 14 | 14 - VMAXWT          | 0.75      | 0 (0.0%)     |
| TH 15 | 15 - QWT             | 0.75      | 0 (0.0%)     |
| TH 16 | 16 - CLAGE           | 0         | 0 (0.0%)     |
+-------+----------------------+-----------+--------------+
+----------+-------+----------+-----------------+
|  OMEGA   |  ETA  | ESTIMATE | SHRINKAGESD (%) |
+----------+-------+----------+-----------------+
| O(1,1)   | ETA1  | 0.089208 | 5.800300        |
| O(2,2)   | ETA2  | 0.033630 | 10.744000       |
| O(3,3)   | ETA3  | 0.326591 | 17.452000       |
| O(4,4)   | ETA4  | 0.000000 | 100.000000      |
| O(5,5)   | ETA5  | 0.000000 | 100.000000      |
| O(6,6)   | ETA6  | 0.000000 | 100.000000      |
| O(7,7)   | ETA7  | 0.039947 | 100.000000      |
| O(8,8)   | ETA8  | 0.039947 | 55.298000       |
| O(9,9)   | ETA9  | 0.039947 | 5.874200        |
| O(10,10) | ETA10 | 0.039947 | 42.844000       |
| O(11,11) | ETA11 | 0.039947 |                 |
| O(12,12) | ETA12 | 0.039947 |                 |
| O(13,13) | ETA13 | 0.039947 |                 |
| O(14,14) | ETA14 | 0.039947 |                 |
| O(15,15) | ETA15 | 0.039947 |                 |
| O(16,16) | ETA16 | 0.039947 |                 |
| O(17,17) | ETA17 | 0.039947 |                 |
| O(18,18) | ETA18 | 0.039947 |                 |
+----------+-------+----------+-----------------+
